GET http://localhost:4000/product-api/products 
### 
GET http://localhost:4000/product-api/products/69b2327fff0bd47dad30eaa3
###
POST http://localhost:4000/product-api/products 
Content-Type: application/json 

{
    "productId":13245,
    "productName":"riya",
    "price":20000,
    "brand":"puma"
   

}
###
PUT http://localhost:4000/product-api/products/69b2530184546d874951f283
Content-Type: application/json 

{
    "productId":13245,
    "productName" : "miya",
    "price":20000,
    "brand":"adidas"


}

###
DELETE http://localhost:4000/product-api/products/69ab9efd98b775bf531fc92e
###




